package leavesanalyzer.core;

public enum SegmentPropertyID {
	AREA,
	ASPECT_RATIO,
	BOUNDING_BOX,
	BREADTH,
	CONVEX_AREA,
	CONVEX_HULL,
	DIAMETER_LINE,
	FORM_FACTOR,
	HU_MOMENT_1,
	HU_MOMENT_2,
	HU_MOMENT_3,
	HU_MOMENT_4,
	HU_MOMENT_5,
	HU_MOMENT_6,
	HU_MOMENT_7,
	HU_MOMENTS,
	LENGTH,
	PERIMETER,
	RATIO_PERIMETER_BREADTH_LENGTH,
	RATIO_PERIMETER_LENGTH,
	RECTANGULARITY,
	ROUNDNESS,
	SOLIDITY
}
